blueprint:
  name: "Advanced Alarm Clock (MASS & Light)"
  description: >
    A comprehensive alarm clock solution featuring both a 'Sunrise' light fade (pre-alarm) 
    and local sound playback (main alarm).
    
    IMPORTANT: This Blueprint requires specific Input Helpers (Booleans, Datetime, Selects, etc.)
    to be created first. Refer to the repository documentation/template for setup instructions.
    
    Features:
    - Dynamic light 'Fade-in' starting X minutes before the main alarm.
    - Local media playback via MASS/Media Player.
    - Checks if the target person is home.
    - Weekday management via external input_booleans (for Dashboard control).
  
  source_url: https://github.com/fredamn76/homeassistant-blueprints/blob/main/automation/advanced_alarm_clock_mass.yaml
  domain: automation
  input:
    # --- MAIN SETTINGS ---
    person_entity:
      name: Person Entity to Check
      description: The alarm will only trigger if this person is 'home'.
      selector:
        entity:
          domain: person
    
    alarm_time_entity:
      name: Alarm Time (Input Datetime)
      description: The helper entity that controls when the sound starts.
      selector:
        entity:
          domain: input_datetime

    alarm_enabled_entity:
      name: Master Switch (Input Boolean)
      description: Main toggle to enable/disable the alarm system.
      selector:
        entity:
          domain: input_boolean

    # --- DAY TOGGLES (UI SWITCHES) ---
    day_monday:
      name: Monday (Input Boolean)
      selector: { entity: { domain: input_boolean } }
    day_tuesday:
      name: Tuesday (Input Boolean)
      selector: { entity: { domain: input_boolean } }
    day_wednesday:
      name: Wednesday (Input Boolean)
      selector: { entity: { domain: input_boolean } }
    day_thursday:
      name: Thursday (Input Boolean)
      selector: { entity: { domain: input_boolean } }
    day_friday:
      name: Friday (Input Boolean)
      selector: { entity: { domain: input_boolean } }
    day_saturday:
      name: Saturday (Input Boolean)
      selector: { entity: { domain: input_boolean } }
    day_sunday:
      name: Sunday (Input Boolean)
      selector: { entity: { domain: input_boolean } }

    # --- LIGHT SETTINGS ---
    target_light:
      name: Light for Wake-up Effect
      selector:
        target:
          entity:
            domain: light
    
    light_offset_entity:
      name: Light Head Start (min)
      description: How many minutes before the main alarm should the light fade begin?
      selector:
        entity:
          domain: input_number

    # --- SOUND SETTINGS ---
    media_player_select:
      name: Speaker Selection (Input Select)
      description: An Input Select containing the entity_ids of the media players.
      selector:
        entity:
          domain: input_select

    media_file_select:
      name: Sound File Selection (Input Select)
      description: An Input Select containing the required media filenames (in /media/local/local/).
      selector:
        entity:
          domain: input_select

    volume_entity:
      name: Volume % (Input Number)
      selector:
        entity:
          domain: input_number

mode: parallel
max: 10

trigger:
  # TRIGGER 1: Light (Pre-Alarm)
  # Uses a template trigger to check every minute if now() == (Alarm Time - Offset)
  - platform: template
    id: "trigger_light"
    value_template: >
      {% set alarm_time_str = states(inputs.alarm_time_entity) %}
      {% set offset_min = states(inputs.light_offset_entity) | int(20) %}
      
      {# Error handling if entities are unavailable #}
      {% if alarm_time_str in ['unknown', 'unavailable'] %}
        false
      {% else %}
        {% set parts = alarm_time_str.split(':') %}
        {% set alarm_h = parts[0] | int(7) %}
        {% set alarm_m = parts[1] | int(0) %}
        
        {# Calculate the light start time for today #}
        {% set alarm_time_today = today_at().replace(hour=alarm_h, minute=alarm_m, second=0) %}
        {% set light_time = alarm_time_today - timedelta(minutes=offset_min) %}
        
        {# Trigger exactly at the calculated light start time #}
        {{ now().strftime('%H:%M') == light_time.strftime('%H:%M') }}
      {% endif %}

  # TRIGGER 2: Sound (Main Alarm)
  - platform: time
    id: "trigger_sound"
    at: !input alarm_time_entity

condition:
  # 1. Master Switch must be ON
  - condition: state
    entity_id: !input alarm_enabled_entity
    state: "on"
  
  # 2. Person must be HOME
  - condition: state
    entity_id: !input person_entity
    state: "home"

  # 3. Correct Weekday must be ON
  - condition: template
    value_template: >
      {% set day_map = {
        0: states(inputs.day_monday),
        1: states(inputs.day_tuesday),
        2: states(inputs.day_wednesday),
        3: states(inputs.day_thursday),
        4: states(inputs.day_friday),
        5: states(inputs.day_saturday),
        6: states(inputs.day_sunday)
      } %}
      {{ day_map[now().weekday()] == 'on' }}

action:
  - choose:
      # --- ACTION: LIGHT (Sunrise Fade) ---
      - conditions:
          - condition: trigger
            id: "trigger_light"
        sequence:
          # Step 1: Turn light on at minimum brightness (to set the color)
          - service: light.turn_on
            target: !input target_light
            data:
              brightness: 1
              rgb_color: [255, 160, 80]
          - delay: "00:00:02"
          # Step 2: Fade to full brightness over the defined offset period
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_pct: 100
              rgb_color: [255, 220, 180]
              # Transition time is offset (minutes) converted to seconds
              transition: "{{ states(inputs.light_offset_entity) | int(20) * 60 }}"

      # --- ACTION: SOUND (Main Alarm) ---
      - conditions:
          - condition: trigger
            id: "trigger_sound"
        sequence:
          # 1. Set Volume
          - service: media_player.volume_set
            target:
              entity_id: "{{ states(inputs.media_player_select) }}"
            data:
              volume_level: "{{ states(inputs.volume_entity) | int(50) / 100 }}"
          
          # 2. Set Repeat (Loop the file)
          - service: media_player.repeat_set
            target:
              entity_id: "{{ states(inputs.media_player_select) }}"
            data:
              repeat: "one"
            continue_on_error: true
            
          # 3. Play Media File
          - service: media_player.play_media
            target:
              entity_id: "{{ states(inputs.media_player_select) }}"
            data:
              media_content_id: "media-source://media_source/local/local/{{ states(inputs.media_file_select) }}"
              media_content_type: audio/mpeg
              metadata:
                title: "{{ states(inputs.media_file_select) }}"
                media_class: music
                children_media_class: null
                navigateIds:
                  - {}
                  - media_content_type: app
                    media_content_id: media-source://media_source
                  - media_content_type: ""
                    media_content_id: media-source://media_source/local/.
                  - media_content_type: ""
                    media_content_id: media-source://media_source/local/local