blueprint:
  name: Battery Monitor (Smart Alert)
  description: >-
    Monitors battery sensors and sends a notification when the level drops below a set threshold.
    QA-Verified: Uses standard MDI icons for system compatibility + Custom Branding.
  source_url: https://github.com/fredamn76/homeassistant-blueprints/blob/main/automation/battery_monitor.yaml
  domain: automation
  input:
    battery_sensors:
      name: Battery Sensors
      description: Select the battery sensors you want to monitor.
      selector:
        entity:
          domain: sensor
          device_class: battery
          multiple: true
    threshold:
      name: Warning Threshold (%)
      description: Trigger notification when battery drops below this level.
      default: 15
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    notify_service:
      name: Notification Service
      description: "Exact service name, e.g., 'notify.mobile_app_iphone'. Leave empty to skip."
      selector:
        text: {}
      default: ""
    notification_logo:
      name: Brand Logo URL
      description: "URL to an image/logo to display in notifications (use Raw GitHub URL)."
      default: "https://raw.githubusercontent.com/fredamn76/homeassistant-blueprints/main/images/logo.jpg"
      selector:
        text: {}
    actions:
      name: Additional Actions (Optional)
      description: "Run extra actions, e.g., TTS to smart speakers."
      default: []
      selector:
        action: {}

trigger:
  - platform: numeric_state
    entity_id: !input battery_sensors
    below: !input threshold

action:
  - variables:
      sensor_name: "{{ trigger.to_state.name }}"
      battery_level: "{{ trigger.to_state.state }}"
      notify_service: !input notify_service
      logo_url: !input notification_logo

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ notify_service != '' }}"
        sequence:
          - service: "{{ notify_service }}"
            data:
              title: "🪫 Low Battery"
              message: "{{ sensor_name }} is down to {{ battery_level }}%."
              data:
                tag: "battery-alert-{{ trigger.entity_id }}"
                channel: "Battery"
                # QA FIX: Standard MDI icon for the notification badge
                icon: "mdi:battery-alert"
                # Custom branding stays as the large image
                image: "{{ logo_url }}"
                push:
                  sound:
                    name: default
                    critical: 0
                    volume: 0.5

  - if:
      - condition: template
        value_template: "{{ true }}"
    then: !input actions

mode: parallel
max: 10
